"""Fail-closed Research Study Layer contracts.

This public facade keeps the eight scientific objects separate from the Aspen execution
control plane. Phase 1 validates immutable study manifests only; it never opens a simulator.
"""

from .research_common import (
    MAX_DOCUMENT_BYTES as MAX_DOCUMENT_BYTES,
    MAX_JSON_DEPTH as MAX_JSON_DEPTH,
    ArtifactRef as ArtifactRef,
    Maturity as Maturity,
    ObjectRef as ObjectRef,
    RESEARCH_SCHEMA as RESEARCH_SCHEMA,
    ResearchObjectType as ResearchObjectType,
    ResearchValidationError as ResearchValidationError,
    SemanticBinding as SemanticBinding,
    SourceRef as SourceRef,
    _boolean as _boolean,
    _canonical_bytes as _canonical_bytes,
    _enum as _enum,
    _finite_number as _finite_number,
    _id as _id,
    _json_object as _json_object,
    _mapping as _mapping,
    _optional_sha256 as _optional_sha256,
    _optional_text as _optional_text,
    _refs as _refs,
    _reject_unknown as _reject_unknown,
    _safe_json as _safe_json,
    _scalar as _scalar,
    _sequence as _sequence,
    _sources as _sources,
    _strings as _strings,
    _text as _text,
    canonical_hash as canonical_hash,
)
from .research_objects import (
    Assumption as Assumption,
    Calibration as Calibration,
    Claim as Claim,
    Dataset as Dataset,
    DatasetVariable as DatasetVariable,
    DatasetVariableRef as DatasetVariableRef,
    Parameter as Parameter,
    Study as Study,
    Target as Target,
    Validation as Validation,
)
from .research_validation import (
    ResearchIssue as ResearchIssue,
    ResearchStudyDocument as ResearchStudyDocument,
    ResearchValidationReport as ResearchValidationReport,
    validate_research_document as validate_research_document,
)

__all__ = [
    "RESEARCH_SCHEMA",
    "ArtifactRef",
    "Assumption",
    "Calibration",
    "Claim",
    "Dataset",
    "DatasetVariable",
    "DatasetVariableRef",
    "Maturity",
    "ObjectRef",
    "Parameter",
    "ResearchIssue",
    "ResearchObjectType",
    "ResearchStudyDocument",
    "ResearchValidationError",
    "ResearchValidationReport",
    "SemanticBinding",
    "SourceRef",
    "Study",
    "Target",
    "Validation",
    "canonical_hash",
    "validate_research_document",
]
